name: Release

on:
  workflow_dispatch:

jobs:
  check_perms:
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        id: is_organization_member
        uses: JamesSingleton/is-organization-member@1.0.0
        with:
          organization: lameduse
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Comment
        if: |
          steps.is_organization_member.outputs.result == false
        run: exit 1
  lint:
    if: github.ref == 'refs/heads/main'
    needs:
      - check_perms
    uses: ./.github/workflows/lint.yaml
    secrets: inherit

  build:
    if: github.ref == 'refs/heads/main'
    needs:
      - check_perms
    uses: ./.github/workflows/build.yaml
    secrets: inherit

  perfom-release:
    if: github.ref == 'refs/heads/main'
    needs:
      - check_perms
      - lint
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release project
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 19.0.2
          branch: main
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/npm
        env:
          GITHUB_TOKEN: ${{ secrets.LAMEDUSE_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.LAMEDUSE_BOT_GIT_AUTHOR_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.LAMEDUSE_BOT_GIT_AUTHOR_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.LAMEDUSE_BOT_GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.LAMEDUSE_BOT_GIT_COMMITTER_EMAIL }}
