name: Build

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

  release:
    types: [published]

  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-skip:
    runs-on: ubuntu-latest
    steps:
      - name: Hello build
        run: echo "Hello Build"
  status-check:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - build-skip
    if: success()
    steps:
      - name: Final status check
        run: echo "All builds succeeded"
